### ISSUE TITLE
On/Off State is not accurate

### ISSUE THREAD

**Issue by alisdairjsmyth** [alisdairjsmyth/homebridge-ambiclimate#3]
As of npm v1.1, each Ambi Climate device is represented as a switch.  Within HomeKit the state of each switch can be queried and viewed, however in many cases the reported state in HomeKit is different to the current operating state in the Ambi Climate App.

**Comment by alisdairjsmyth** [comment]
The primary constraint is that the Ambi Labs public API does not provide a mechanism to query the current operating mode or be notified of a change.  Because of this the state is defaulted at start-up and maintained within the plugin based on state operations it handles.  As such changes initiated through other channels (e.g. Ambi Climate App) will not be reflected in HomeKit.

**Comment by jychen7** [comment]
@alisdairjsmyth I find "Get Ambi Climate's current working mode" in https://api.ambiclimate.com/doc/api#mode, is it what you need?

**Comment by alisdairjsmyth** [comment]
@jychen7 - I think so.  Unfortunately I will not be able to look at this till next weekend, but I suspect this API is an appropriate mechanism.
