### ISSUE TITLE
Homebridge Crash 

### ISSUE THREAD

**Issue by araa47** [alisdairjsmyth/homebridge-ambiclimate#6]

**Comment by alisdairjsmyth** [comment]
The Ambi Climate API only provides access tokens through the "authorization code grant".  This process requires a human confirmation.  The subsequently created token has validity for only 14400 seconds (issue #5).  When the token expires it causes, the present handling causes Homebridge to crash (issue #4).

I am presently exploring whether a token refresh mechanism can be incorporated.

**Comment by alisdairjsmyth** [comment]
FYI - The current version 2.1.0 addresses the issue you experienced.  It now includes a OAUTH client which requests and manages the bearer token, thereby avoiding its expiry.
